local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("GuPr0 Hub X Boxfruits", "BloodTheme")

local Tab = Window:NewTab("MENU")
local Section = Tab:NewSection("Script Boxfruits")
Section:NewButton("Run ScriptBoxfruits", "Run By. GuPr0 Hub", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/natoppo044/modzcaster/main/Bfip.lua")()
end)

local Tab = Window:NewTab("INFO")
local Section = Tab:NewSection("Info Team GuPr0")
Section:NewButton("Info", "Make By. GuPr0 Hub 2022", function()
end)
Section:NewButton("Github", "https://github.com/Deemming998 //GitHub", function()
end)
Section:NewButton("Pastebin", "https://pastebin.com/u/GuPr0Hub //Pastebin", function()
end)
