local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("GuPr0 Hub", "BloodTheme")
 
local Tab = Window:NewTab("MENU")
local Section = Tab:NewSection("Script Boxfuit")
Section:NewButton("Run ScriptBoxfuit", "Make By. GuPr0 Hub", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/natoppo044/modzcaster/main/Bfip.lua")()
end)
local Section = Tab:NewSection("Comming Soon!!")
 
local Tab = Window:NewTab("INFO")
local Section = Tab:NewSection("Info Team GuPr0")
Section:NewButton("Info", "Make By. GuPr0 Hub 2022", function()
end)
Section:NewButton("GITHUB", "https://github.com/Deemming998 //GitHub", function()
end)
Section:NewButton("Pastebim", "https://pastebin.com/u/GuPr0Hub //Pastebin", function()
end)
